name: CI

on:
  pull_request:
  push:
    branches:
      - master
      - releases/*
    tags:
      - v*
env:
  DOCKER_HOST: unix:///var/run/docker.sock

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '10.0.x'
      - name: checkout
        uses: actions/checkout@v6
        with: 
          fetch-tags: true
      - name: build
        shell: bash
        run: dotnet build --configuration Release
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '10.0.x'
      - name: checkout
        uses: actions/checkout@v6
        with:
          fetch-tags: true
      - name: test
        shell: bash
        run: dotnet test --configuration Release tests/SqlStreamStore.Tests --logger GitHubActions

  test-implementation:
    needs: build
    strategy:
      fail-fast: false
      matrix:
        test: [ "MsSql", "MsSql.V3", "MySql", "Postgres", "Sqlite", "HAL", "Http" ]

    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '10.0.x'
      - name: checkout
        uses: actions/checkout@v6
        with:
          fetch-tags: true
      - name: test
        shell: bash
        run: dotnet test --configuration Release tests/SqlStreamStore.${{ matrix.test }}.Tests  --logger GitHubActions
  
  coverage:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    needs:
      - test
      - test-implementation
    steps:
      - uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '10.0.x'
      - name: checkout
        uses: actions/checkout@v6
        with:
          fetch-tags: true
      - name: cover
        shell: bash
        run: |
          dotnet test \
            /p:CollectCoverage=true \
            /p:CoverletOutput=TestResults \
            /p:CoverletOutputFormat="cobertura" || true
      - name: restore tools
        shell: bash
        run: dotnet tool restore
      - name: collect
        shell: bash
        env:
          TESTINGPLATFORM_EXITCODE_IGNORE: 1
        run: |
          dotnet reportgenerator \
          -reports:"**/TestResults.cobertura.xml" \
          -targetdir:.coverage-reports \
          -reporttypes:"Markdown;MarkdownSummaryGithub"
      - name: report
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          recreate: true
          path: .coverage-reports/SummaryGithub.md
  publish:
    permissions:
      packages: write
      contents: read
    needs:
      - test
      - test-implementation
    runs-on: ubuntu-latest
    name: package
    steps:
      - uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '10.0.x'
      - name: checkout
        uses: actions/checkout@v6
        with:
          fetch-tags: true
      - name: pack
        shell: bash
        run: dotnet pack --configuration Release --output publish
      - name: publish
        if: github.event_name != 'pull_request'
        shell: bash
        run: |
          dotnet nuget push publish/*.nupkg \
            --api-key ${{secrets.GITHUB_TOKEN}} \
            --source  https://nuget.pkg.github.com/thefringeninja/index.json
